/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface KRAEntry {
  'id' : bigint,
  'period' : string,
  'selfRating' : [] | [Rating],
  'createdAt' : Time,
  'createdBy' : Principal,
  'particulars' : string,
  'hodRating' : [] | [Rating],
}
export interface PeriodSummary {
  'totalEntries' : bigint,
  'period' : string,
  'averageHODRating' : [] | [number],
  'averageSelfRating' : [] | [number],
}
export type Rating = number;
export type Time = bigint;
export interface UserProfile { 'name' : string, 'employeeId' : [] | [string] }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createKRAEntry' : ActorMethod<[string, string], bigint>,
  'deleteKRAEntry' : ActorMethod<[bigint], undefined>,
  'getAllKRAEntries' : ActorMethod<[], Array<KRAEntry>>,
  'getAllSummaries' : ActorMethod<[], Array<PeriodSummary>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getKRAEntriesByPeriod' : ActorMethod<[string], Array<KRAEntry>>,
  'getKRAEntry' : ActorMethod<[bigint], [] | [KRAEntry]>,
  'getMyKRAEntries' : ActorMethod<[], Array<KRAEntry>>,
  'getSummaryByPeriod' : ActorMethod<[string], PeriodSummary>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'submitHODRating' : ActorMethod<[bigint, Rating], undefined>,
  'submitSelfRating' : ActorMethod<[bigint, Rating], undefined>,
  'updateKRAEntry' : ActorMethod<[bigint, string, string], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];