/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Rating = IDL.Nat32;
export const Time = IDL.Int;
export const KRAEntry = IDL.Record({
  'id' : IDL.Nat,
  'period' : IDL.Text,
  'selfRating' : IDL.Opt(Rating),
  'createdAt' : Time,
  'createdBy' : IDL.Principal,
  'particulars' : IDL.Text,
  'hodRating' : IDL.Opt(Rating),
});
export const PeriodSummary = IDL.Record({
  'totalEntries' : IDL.Nat,
  'period' : IDL.Text,
  'averageHODRating' : IDL.Opt(IDL.Float64),
  'averageSelfRating' : IDL.Opt(IDL.Float64),
});
export const UserProfile = IDL.Record({
  'name' : IDL.Text,
  'employeeId' : IDL.Opt(IDL.Text),
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createKRAEntry' : IDL.Func([IDL.Text, IDL.Text], [IDL.Nat], []),
  'deleteKRAEntry' : IDL.Func([IDL.Nat], [], []),
  'getAllKRAEntries' : IDL.Func([], [IDL.Vec(KRAEntry)], ['query']),
  'getAllSummaries' : IDL.Func([], [IDL.Vec(PeriodSummary)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getKRAEntriesByPeriod' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(KRAEntry)],
      ['query'],
    ),
  'getKRAEntry' : IDL.Func([IDL.Nat], [IDL.Opt(KRAEntry)], ['query']),
  'getMyKRAEntries' : IDL.Func([], [IDL.Vec(KRAEntry)], ['query']),
  'getSummaryByPeriod' : IDL.Func([IDL.Text], [PeriodSummary], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'submitHODRating' : IDL.Func([IDL.Nat, Rating], [], []),
  'submitSelfRating' : IDL.Func([IDL.Nat, Rating], [], []),
  'updateKRAEntry' : IDL.Func([IDL.Nat, IDL.Text, IDL.Text], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Rating = IDL.Nat32;
  const Time = IDL.Int;
  const KRAEntry = IDL.Record({
    'id' : IDL.Nat,
    'period' : IDL.Text,
    'selfRating' : IDL.Opt(Rating),
    'createdAt' : Time,
    'createdBy' : IDL.Principal,
    'particulars' : IDL.Text,
    'hodRating' : IDL.Opt(Rating),
  });
  const PeriodSummary = IDL.Record({
    'totalEntries' : IDL.Nat,
    'period' : IDL.Text,
    'averageHODRating' : IDL.Opt(IDL.Float64),
    'averageSelfRating' : IDL.Opt(IDL.Float64),
  });
  const UserProfile = IDL.Record({
    'name' : IDL.Text,
    'employeeId' : IDL.Opt(IDL.Text),
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createKRAEntry' : IDL.Func([IDL.Text, IDL.Text], [IDL.Nat], []),
    'deleteKRAEntry' : IDL.Func([IDL.Nat], [], []),
    'getAllKRAEntries' : IDL.Func([], [IDL.Vec(KRAEntry)], ['query']),
    'getAllSummaries' : IDL.Func([], [IDL.Vec(PeriodSummary)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getKRAEntriesByPeriod' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(KRAEntry)],
        ['query'],
      ),
    'getKRAEntry' : IDL.Func([IDL.Nat], [IDL.Opt(KRAEntry)], ['query']),
    'getMyKRAEntries' : IDL.Func([], [IDL.Vec(KRAEntry)], ['query']),
    'getSummaryByPeriod' : IDL.Func([IDL.Text], [PeriodSummary], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'submitHODRating' : IDL.Func([IDL.Nat, Rating], [], []),
    'submitSelfRating' : IDL.Func([IDL.Nat, Rating], [], []),
    'updateKRAEntry' : IDL.Func([IDL.Nat, IDL.Text, IDL.Text], [], []),
  });
};

export const init = ({ IDL }) => { return []; };